identity:
  key_file: "worker.key"
network:
  listen_port: 4002
  min_peers: 50
  max_peers: 100
  bootstrap_addrs:
    - "/ip4/140.238.226.231/tcp/4001/p2p/12D3KooWL3djSAb7XWKMGVZCNbQEchV9s3TKcbgx2Fm1E34Rqeaa"
discovery:
  rendezvous: "evm-pmpc-rendezvous-room"
  protocol_prefix: "/evm-pmpc-node/0.1.0"
logging:
  level: "info"
  format: "console"
